### ISSUE TITLE
All java source files are without license headers

### ISSUE THREAD

**Issue by puntogil** [rometools/rome-utils#2]
Hi,
Please, add license headers and confirm the licensing of code and/or content/s
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification
This issue block https://bugzilla.redhat.com/show_bug.cgi?id=1185275
Thanks in advance

**Comment by mishako** [comment]
Moved this issue to https://github.com/rometools/rome/issues/220 as part of https://github.com/rometools/rome/issues/217

@PatrickGotthard Could you please close this issue and disable issues in rome-utils? Apparently I don't have write access.
